### ISSUE TITLE
Options in quotes don't get defined correctly

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#71] opened 2015-02-03 02:42 UTC
<code>vv create</code> is adding an extra <code>/</code> after the themes directory which is causing an error.

<code>
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
</code>

**Comment by bradp** [comment] 2015-02-03 03:23
What was the domain you used to create this site? Did that have a slash at the end?

**Comment by clreed87** [comment] 2015-02-03 03:32
No just <code>test123.dev</code> -- I actually accepted the default domain in the wizard when I entered the directory.

**Comment by bradp** [comment] 2015-02-03 03:44
Can you paste the contents of vvv-init.sh for me? I just made a new site, and couldn't reproduce this error.

**Comment by clreed87** [comment] 2015-02-03 03:57
Sure--let me re-create one. I did create from a blueprint so maybe thats the culprit.

**Comment by clreed87** [comment] 2015-02-03 04:09
<code>
if [ ! -d "htdocs/wp-admin" ]; then
	echo 'Installing WordPress (release version) in test123/htdocs...'
	if [ ! -d "./htdocs" ]; then
		mkdir ./htdocs
	fi
	cd ./htdocs
	wp core download --allow-root 
	wp core config --dbname="test123" --dbuser=wp --dbpass=wp --dbhost="localhost" --allow-root
	wp core install --url=test123.dev --title="test123" --admin_user=admin --admin_password=password --admin_email=admin@localhost.dev --allow-root
	
	
	
	cd -
curl -o vv-install -s https://raw.githubusercontent.com/bradp/vv/vv-install/vv-install && php vv-install ChrisReedTech htdocs && rm vv-blueprints.json
fi
</code>

**Comment by bradp** [comment] 2015-02-03 13:48
It looks like the issue is that you've set WordPress to use a theme that doesn't exist, or to not use a theme, this might be an issue with your blueprint.

**Comment by clreed87** [comment] 2015-02-03 17:07
Sure if you don't mind:

<code>
{
  "ChrisReedTech": {
    "themes": [
      "https://www.dropbox.com/s/07ak9m7gfdzra2u/genesis.zip?dl=1",
      "https://www.dropbox.com/s/kyezmat8eem1gxh/genesis-sample.zip?dl=1"
    ],
    "plugins": [
      "https://github.com/clreed87/crt-plugin.git",
      "https://www.dropbox.com/s/y9idalsee1t9guq/advanced-custom-fields-pro.zip?dl=1",
      "akismet",
      "backwpup",
      "codepress-admin-columns",
      "genesis-enews-extended",
      "genesis-featured-content-widget",
      "genesis-simple-share",
      "google-analytics-for-wordpress",
      "iwp-client",
      "jetpack",
      "menu-humility",
      "ninja-forms",
      "regenerate-thumbnails",
      "simple-social-icons",
      "w3-total-cache",
      "wordpress-seo"
    ],
    "options": [
      "date_format::'F j, Y'",
      "time_format::'g:i a'",
      "permalink_structure::'/%postname%/'",
      "ping_sites::'http://rpc.pingomatic.com/\nhttp://ping.blo.gs/\nhttp://ping.feedburner.com\nhttp://api.my.yahoo.co.jp/RPC2\nhttp://audiorpc.weblogs.com/RPC2\nhttp://bblog.com/ping.php\nhttp://bing.com/webmaster/ping.aspx\nhttp://blo.gs/ping.php\nhttp://blog.goo.ne.jp\nhttp://blog.goo.ne.jp/XMLRPC\nhttp://blog.iask.com/rpc2\nhttp://blog.with2.net/ping.php\nhttp://blogpeople.net/ping\nhttp://blogpeople.net/servlet/weblogUpdates\nhttp://blogping.unidatum.com/RPC2\nhttp://blogpingr.de/ping/rpc2\nhttp://blogroots.com\nhttp://blogs.yandex.ru\nhttp://blogsdominicanos.com/ping\nhttp://blogsearch.google.ae/ping/RPC2\nhttp://blogsearch.google.at/ping/RPC2\nhttp://blogsearch.google.be/ping/RPC2\nhttp://blogsearch.google.bg/ping/RPC2\nhttp://blogsearch.google.ca/ping/RPC2\nhttp://blogsearch.google.ch/ping/RPC2\nhttp://blogsearch.google.cl/ping/RPC2\nhttp://blogsearch.google.co.cr/ping/RPC2\nhttp://blogsearch.google.co.hu/ping/RPC2\nhttp://blogsearch.google.co.id/ping/RPC2\nhttp://blogsearch.google.co.il/ping/RPC2\nhttp://blogsearch.google.co.in/ping/RPC2\nhttp://blogsearch.google.co.it/ping/RPC2\nhttp://blogsearch.google.co.jp/ping/RPC2\nhttp://blogsearch.google.co.ma/ping/RPC2\nhttp://blogsearch.google.co.nz/ping/RPC2\nhttp://blogsearch.google.co.th/ping/RPC2\nhttp://blogsearch.google.co.uk/ping/RPC2\nhttp://blogsearch.google.co.ve/ping/RPC2\nhttp://blogsearch.google.co.za/ping/RPC2\nhttp://blogsearch.google.com.ar/ping/RPC2\nhttp://blogsearch.google.com.au/ping/RPC2\nhttp://blogsearch.google.com.br/ping/RPC2\nhttp://blogsearch.google.com.co/ping/RPC2\nhttp://blogsearch.google.com.do/ping/RPC2\nhttp://blogsearch.google.com.mx/ping/RPC2\nhttp://blogsearch.google.com.my/ping/RPC2\nhttp://blogsearch.google.com.pe/ping/RPC2\nhttp://blogsearch.google.com.sa/ping/RPC2\nhttp://blogsearch.google.com.sg/ping/RPC2\nhttp://blogsearch.google.com.tr/ping/RPC2\nhttp://blogsearch.google.com.tw/ping/RPC2\nhttp://blogsearch.google.com.ua/ping/RPC2\nhttp://blogsearch.google.com.uy/ping/RPC2\nhttp://blogsearch.google.com.vn/ping/RPC2\nhttp://blogsearch.google.com/ping/RPC2\nhttp://blogsearch.google.de/ping/RPC2\nhttp://blogsearch.google.es/ping/RPC2\nhttp://blogsearch.google.fi/ping/RPC2\nhttp://blogsearch.google.fr/ping/RPC2\nhttp://blogsearch.google.gr/ping/RPC2\nhttp://blogsearch.google.hr/ping/RPC2\nhttp://blogsearch.google.ie/ping/RPC2\nhttp://blogsearch.google.it/ping/RPC2\nhttp://blogsearch.google.jp/ping/RPC2\nhttp://blogsearch.google.lt/ping/RPC2\nhttp://blogsearch.google.lv/ping/rpc2\nhttp://blogsearch.google.nl/ping/RPC2\nhttp://blogsearch.google.pl/ping/RPC2\nhttp://blogsearch.google.pt/ping/RPC2\nhttp://blogsearch.google.ro/ping/RPC2\nhttp://blogsearch.google.ru/ping/RPC2\nhttp://blogsearch.google.se/ping/RPC2\nhttp://blogsearch.google.sk/ping/RPC2\nhttp://blogsearch.google.tw/ping/RPC2\nhttp://blogsearch.google.us/ping/RPC2'",
      "template::'genesis'",
      "stylesheet::'genesis-sample'",
      "timezone_string::'America/Chicago'",
      "current_theme::'Genesis Sample Theme'"
    ],
    "defines": [
      "JETPACK_DEV_DEBUG::true"
    ]
  }
}
</code>

**Comment by bradp** [comment] 2015-02-03 17:13
Looks like the issue is the quotes in the options section, I don't believe VV supports those too well right now.

I'd suggest trying removal of those quotes, and if that still doesn't work, I'll figure out a patch for it.

Thanks!

**Comment by clreed87** [comment] 2015-02-03 17:16
Ah I put the quotes around the options because one of the strings had all those line breaks and that seemed to be breaking the options setup. I thought the quotes had fixed that problem but may have caused another.

**Comment by bradp** [comment] 2015-02-03 17:17
Yeah, I'll make sure to add support to quoting those variables.

**Comment by clreed87** [comment] 2015-02-03 17:21
Awesome. Thanks for being so responsive. Let me know if there's anything I can help test or anything else you need.

**Comment by clreed87** [comment] 2015-02-05 02:33
I;m actually note sure if the quotes are the problem. I only added the two options to set my theme template to my blueprint:

<code>
    "options": [
      "template::genesis",
      "stylesheet::genesis-sample"
    ],
</code>

And still get this error:

<code>
==> default: PHP Warning:  require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Warning:  require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Warning: require(/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php): failed to open stream: No such file or directory in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: PHP Fatal error:  require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
==> default: Fatal error: require(): Failed opening required '/srv/www/Test2/htdocs/wp-content/themes//inc/custom-header.php' (include_path='/srv/www/wp-cli/vendor/phpunit/php-text-template:/srv/www/wp-cli/vendor/phpunit/phpunit-mock-objects:/srv/www/wp-cli/vendor/phpunit/php-timer:/srv/www/wp-cli/vendor/phpunit/php-token-stream:/srv/www/wp-cli/vendor/phpunit/php-file-iterator:/srv/www/wp-cli/vendor/phpunit/php-code-coverage:/srv/www/wp-cli/vendor/phpunit/phpunit:/srv/www/wp-cli/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /srv/www/Test2/htdocs/wp-content/themes/twentyfifteen/functions.php on line 317
</code>

**Comment by bradp** [comment] 2015-02-05 02:52
The issue is that your theme isn't being set correctly. Try setting both "template" and "stylesheet" to your theme name.

**Comment by clreed87** [comment] 2015-02-05 03:00
Well since its Genesis the template is the stylesheet in the Genesis parent theme and the stylesheet is the child theme.  But good idea--I'll try that and see what happens.

**Comment by clreed87** [comment] 2015-02-05 03:01
It's no big deal at all to just set manually after the install--just would like to know the root of the issues now :)

**Comment by clreed87** [comment] 2015-02-05 03:56
Yep--Removed both the stylesheet and template options and everything worked fine (including the items in quotes).  So that seems to be the issues, which is a little strange because the values I was passing are the exact same values in the database after I manually change the theme.

**Comment by bradp** [comment] 2015-03-15 15:24
Fixed in 324c8ce9b82d.

**Closed by bradp** 2015-03-15 15:24 UTC
Labels: blueprints
