### ISSUE TITLE
Unabled to Access New Site

### ISSUE THREAD

**Issue by benlumia007** [bradp/vv#324] opened 2016-11-07 23:57 UTC
It seems like its skipping a step where it should be installing database and htdocs etc. but its not. I tried so many times and it still doesn't work. is there a solution for this.

**Comment by VWinDev** [comment] 2016-11-08 08:22
Even I tried several times it successfully complete the process but it doesn't create htdocs folder and when I check phpmyadmin it creates empty database.

I tried all the fixes mentioned here but none worked for me.

please help us

**Comment by dseidl** [comment] 2016-11-08 13:43
same here

**Comment by benlumia007** [comment] 2016-11-08 17:09
I haven't figured it out yet, still ahving issues, but what am doing right for those who wants to try. I'm using a MacOS and here's what im trying to do right now. 

I downgraded VirtualBox to 5.1.6
I downloaded the latest development version of VVV
I also downloaded the latest development version of VV

I will give you the result soon.

**Comment by benlumia007** [comment] 2016-11-08 18:27
So i got my to work finally 

Use the following 
VirtualBox 5.1.6
VVV version 1.4.0 
VV version 1.12 which i believe the latest one. 

my works now.

**Comment by VWinDev** [comment] 2016-11-09 06:53
Do you think the problem is with virtualbox version? Im using 5.1.8

**Comment by benlumia007** [comment] 2016-11-09 07:02
@VWinDev 
I do because when I was using VirtualBox 5.1.8 and I had a clean Vagrant 1.8.7 with the latest development of VVV and VV, and when I did vagrant up, it give me something about it couldn't let me download the ubuntu/trusty64 box. Then I went and ahead and downgrade to VirtualBox 5.1.6 with the latest development of VVV and VV and I went ahead and did vagrant up and it downloaded the box and continue on to finished, and VVV worked, but with VV, it still didn't work. 

From here, since VV didn't work. I end up thinking that, with Virtualbox 5.1.6 and the latest VVV worked. i started to think that maybe the VVV had issues where you try to use vv, so I deleted VVV and downloaded the vvv 1.4.0 version and I installed successfully and did vv and it worked.

I hope that it make sense. What i thought about was, some people would end up doing bleeding versions which are beta versions and think that's where the problem lies. So I decided just use stable versions of virtualbox and VVV and vv that i know it works, i just keep it as it is.

**Comment by VWinDev** [comment] 2016-11-09 07:07
Ok thanks for your guidance, but how to downgrade the virtualbox?

**Comment by benlumia007** [comment] 2016-11-09 07:12
if you're on MacOS, you should be able just delete it from the /Application

**Comment by VWinDev** [comment] 2016-11-09 07:19
Im using windows, you mean completely uninstall VB and reinstall the older version and then install VVV and VV again?

My problem is vv creates all the necessary files but a blank database and htdocs folder is not getting created. Even tried vagrant provision after vv does its job but all I see is a blank database and neccessary files, and htdocs is still missing.

**Comment by benlumia007** [comment] 2016-11-09 07:21
yeah i had that problem with my MacOS, but my PC works because I was using VirtualBox 5.1.6, so you would have to uninstall VirtualBox 5.1.8 and the extension as well, then you install the older version of VirtualBox 5.1.6 and try again with the same VVV and VV.

**Comment by VWinDev** [comment] 2016-11-09 07:23
Ok how about vagrant version 1.8.7? Im using 1.8.6,

My pc has
virtual box 5.1.8
vagrant 1.8.6
vvv 1.4.0
vv 1.12

**Comment by benlumia007** [comment] 2016-11-09 07:27
i would recommend keeping 1.8.6 because if you get this to work. keep it as it. it is not necessary to upgrade everytime when there's new version. to me that's pointless and leads to problems.
 
On My PC
I have the following Items

* VirtualBox Version 5.1.6
* Vagrant 1.8.6
* VVV (1.4.0)
* VV (1.12)

**Comment by VWinDev** [comment] 2016-11-09 07:38
Actually it takes more time to do all this steps around 2hrs :-( 

but I'll give it a try

Thanks for your support

**Comment by VWinDev** [comment] 2016-11-09 08:01
@benlumia007
The guest additions on this VM do not match the installed version of VirtualBox! Do you get this? and still VVV and VV working fine?

**Comment by benlumia007** [comment] 2016-11-09 08:03
you will need to install that extension version 5.1.6 as well, 
http://download.virtualbox.org/virtualbox/5.1.6/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack and uninstall the 5.1.8 version.

**Comment by VWinDev** [comment] 2016-11-09 08:14
Ok and let see what @bradp  has to say for such issue. It would be great if he could come here and guide for a better solutions.

**Comment by benlumia007** [comment] 2016-11-09 08:16
yeah but just to point out that vv is based on vvv and vvv uses vagrant to do all the work.  in other words, vv just extends the feature to allow users to create multiple sites since vvv does not do that.

**Comment by VWinDev** [comment] 2016-11-09 08:19
Since I have a blank database and all the files setting ready in the folder for example test.dev(created during vv create), can we create htdocs folder ourselves and put the latest WordPress files in there and install manually? Is it something we could do? when vv create doest create htdocs folder?

**Comment by benlumia007** [comment] 2016-11-09 08:25
vv creates everything for you such as creating the folder, adds htdocs, installs WordPress, installs database and creates username and password for database and adds the test.dev to the hosts file that's about it.

**Comment by VWinDev** [comment] 2016-11-09 08:33
No no
What vv creates (example testsite.dev)
1) **testsite** folder in **www**
2) vvv-hosts, vvv-init, wp-cli inside **testsite** folder
3)  Create file testsite.conf inside nginx-config/sites/
4) Empty database name **testsite** in phpmyadmin

What vv doesn't create
1) **htdocs** folder

How can we install the WordPress manually in the scenario as above.

**Comment by dseidl** [comment] 2016-11-09 09:10
You could hook in the vv process and install wp manually with a shell script.
But thats not the solution to this problem.

**Comment by VWinDev** [comment] 2016-11-09 10:02
Yeah it is not a right solution but we can follow it until the @bradp help us fix the issue.

BTW how to run the shell script could you please guide me, actually I'm fed up install the VVV and VV many times since last Friday and have no more patience or time to work on it.

**Comment by VWinDev** [comment] 2016-11-09 14:32
I think there is a issue with provision.sh
==> default: PHPMyAdmin already installed.
==> default: Network connection detected...
==> default: **This is where the site gets created but it doesn't happen**
==> default: **This is where the site gets created but it doesn't happen**
==> default: Cleaning the virtual machine's /etc/hosts file...

I dont understand why the VVV doesn't execute the code when it reach the above break point. If it gets fixed then there would no issue. 

can anyone help to fix it

**Comment by dseidl** [comment] 2016-11-09 14:35
Right now i have no time to look at this further.
But you can do it totally manually until brad or someone else can fix this here.
Just create the htdocs folder and pull in wordpress. You just need to do the normal WP setup process. So fill in db credentials and install it. DB and nginx config should be installed right via vv create.

**Comment by VWinDev** [comment] 2016-11-10 12:09
@dseidl Ok I will follow your idea.

@benlumia007 I followed installing the version of VM box you mentioned but still have the same issue. :-(

**Comment by Kyaviger** [comment] 2016-11-10 15:26
@VWinDev Download vvv 1.3.0

**Comment by benlumia007** [comment] 2016-11-10 15:39
sorry if that didn't work, I've done a lot of testing and I guess it doesn't work for some people. I agree with @Kyaviger  try downloading vvv 1.3.0.

Make sure that you have Microsoft Visual C++ 2008 - 2010, 2013, 2014, 2015 just in case, sometimes these make a lot of difference.

**Comment by VWinDev** [comment] 2016-11-14 18:49
Im follow @dseidl  advice for now, but I don't have time to downgrade vvv and reinstalling the stuff which consumed many hours. but @bradp  would help us that would be great.

**Comment by sdulaney** [comment] 2016-11-15 04:03
After running vv create and no htdocs folder created, I got mine to work by running the script vvv-init.sh from the vagrant server: 

`cd dev/vagrant-local # Use location of vagrant-local on your machine`
`vagrant ssh`
`cd /srv/www/Your-Site-Name`
`./vvv-init.sh`

VirtualBox 5.1.8
Vagrant 1.8.7
VVV 1.4.0
VV 1.12

**Comment by VWinDev** [comment] 2016-11-15 06:47
@sdulaney thanks a lot, it worked for me 👍

**Comment by certainlyakey** [comment] 2016-11-15 14:54
The tip by @sdulaney is really working. Thanks!

**Comment by benlumia007** [comment] 2016-11-21 00:30
My Setup now is
VirtualBox 5.1.6
Vagrant 1.8.5
vvv 1.4.0
vv 1.12

**Comment by U1074958** [comment] 2016-11-22 23:48
Thanks @sdulaney you just saved me a lot of time!

**Comment by AdamQuadmon** [comment] 2016-11-28 18:57
sorry @benlumia007 for the thumb down, even if using your same versions still have this issue and the only solution is a manual init like @sdulaney said.

**Comment by benlumia007** [comment] 2016-11-28 22:23
@AdamQuadmon yeah, but i guess like what i said before, it only works if it lets you or finding different solution like what @sdulaney did make sense, but i think there's no root cause because, i have like one mac and 3 pc, but 3 o fmy pc have different configurations so, as long as it works for me, i'm not going to touch it.

**Comment by benlumia007** [comment] 2016-11-30 01:14
ahh so another working scenario which doesn't make no sense to me,  I had Visual Studio 2015 installed and it seems like it doesn't work well when i try to use VVV for the first time, but when i did  clean install without Visual Studio 2015, and i downloaded the latest software as below. everything works. 

VirtualBox 5.1.10
Vagrant 1.9.0
VVV 1.4.0
vvv 1.12

and it works fine... sigh.

**Comment by sdulaney** [comment] 2016-12-01 16:13
Fixed in bradp/vv#326 after reading Varying-Vagrant-Vagrants/VVV#980, lots of cool new VVV features explained there :+1:

**Comment by benlumia007** [comment] 2016-12-04 05:20
Just to throw out here, I believe the box also makes a difference too. when you vagrant up for the first time. it downloads a certain box for it. from what i know which one works well is the 20161121.0.0. with the latest software 

VirtualBox 5.1.10
Vagrant 1.9.0
VVVV 1.4.0
VV 1.12

**Comment by jonathantneal** [comment] 2016-12-21 17:17
Because it hasn’t explicitly been said, the default vvv branch is `develop`, and switching it to `master` resolves this error. If you prefer to stay on the `develop` branch, @sdulaney’s method is the best workaround.

```sh
cd path/to/your/vagrant-local
vagrant ssh
cd /srv/www/your-site
./vvv-init.sh
```

I’m sorry I don’t yet understand all the [changes coming to vvv](https://github.com/Varying-Vagrant-Vagrants/VVV/pull/980), but those changes are in the `develop` branch. They seem to be related to more easily spinning up sites. I’m interested to know; are they intended to replace functionality we currently get from vv, or is vv intending to work using their new methods? Both?

**Closed** 2017-01-10 14:34 UTC
