### ISSUE TITLE
VV sites 404 not found.

### ISSUE THREAD

**Issue by dterr009** [bradp/vv#340] opened 2017-02-17 18:18 UTC
Hello,

I'm having trouble with new sites created by VV. All of the default sites are working but the new ones get a 404 not found.

Here is my debug

`$ vv --debug-vv
----------
/c/Dev/vv/vv: line 1506: version: command not found

vv: /c/Dev/vv/vv

vv_config: /c/Users/domin/.vv-config
vvv path:        /c/dev/vvv
home: /c/Users/domin

tput:
cat: /usr/bin/cat
curl: /mingw64/bin/curl
which: no brew in (/c/Users/domin/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/domin/bin:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/HashiCorp/Vagrant/bin:/cmd:/c/Users/domin/AppData/Local/Microsoft/WindowsApps:/c/Dev/vv:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/domin/bin)
brew:
tar: /usr/bin/tar
find: /usr/bin/find
git: /mingw64/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /c/HashiCorp/Vagrant/bin/vagrant
`

**Comment by alejuu** [comment] 2017-02-17 20:28
Same here

**Comment by vitolob** [comment] 2017-02-19 01:42
It seems that, for some reason, the vvv-init.sh script is not being run on provision so that we have to run it manually.

You're going to have to ssh into the machine.
`cd /srv/www/{your_site_path}`
Execute `./vvv-init.sh`
Now run `sudo service nginx restart`

I hope that helps while the issue is not yet solved.

**Comment by pixleight** [comment] 2017-02-23 18:03
I've also run into the same issue, also referenced in #339. It appears that provisioning is not running `vvv-init.sh` and I've had to run it manually.

**Comment by Quaked** [comment] 2017-03-03 14:22
Same, question is how we remedy this rather than having to do it manually.

**Comment by butrflied** [comment] 2017-03-04 19:16
I also had this problem today .. and its my first day using VVV & vv. I'm very glad I found this thread, thought I was going crazy :)

**Comment by vitolob** [comment] 2017-03-09 23:05
> Same, question is how we remedy this rather than having to do it manually.
The problem seems to be with a certain incompatibility between vv and the new provisioning system used by VVV.

vv as it is right now works perfectly with the latest stable release of VVV, but fortunately it can also work with the new provisioning system with some tweaks.

Therefore, there are two ways to go about this:

1. Clone the master branch (stable release) of VVV and vv will work with no problems or,

2. Make some tweaks:

I am going to copy/paste @matthewmcvickar comment from the issue https://github.com/bradp/vv/issues/330

> You need to add your site to the vvv-custom.yml file in the root of the VVV installation. For example, if you are adding a site called macgraphic.dev:
> 
> 1. In the root of the VVV installation (the vagrant-local folder), duplicate the vvv-config.yml file and name the copy vvv-custom.yml.
> 
> 2. Add your site to the vvv-custom.yml file:
> `---
> sites:
>   wordpress-default:
>     repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
>     hosts:
>       - local.wordpress.dev
> 
>   macgraphic:
>     hosts:
>       - macgraphic.dev`
> 
> (Leave the rest of the file alone. It is run instead of vvv-config.yml, not in addition to it, so you need to leave in the default WP installations if you still want them.)
> 
> 3.Create your site: vv create macgraphic
> 
> VV will then create the site as expected.

**Comment by estevancarlos** [comment] 2017-03-11 22:28
I get a command now found when entering `sudo service nginx restart`. Suggestions on how to resolve that?

**Comment by vitolob** [comment] 2017-03-12 11:19
Hi @estevancarlos . I imagine you are trying to manually run the vvv-init.sh script. 
For that, you first need to ssh into the machine by running `vagrant ssh` (Assuming you're not on Windows, or are using  Bash). 
Then you can run the commands as suggested.

Did that happen after ssh'ing into the machine?

**Comment by bradp** [comment] 2017-03-17 16:51
Closing this, I'm going to start tracking 2.0 support in https://github.com/bradp/vv/issues/348.

**Closed by bradp** 2017-03-17 16:51 UTC
